name: docker-image-workflow

on:
    push:
    workflow_dispatch:

jobs:
    docker:
        runs-on: ubuntu-latest
        env:
            USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            PASSWORD: ${{ secrets.MY_SECRET_TOKEN_DOKERHUB }}
        steps:
            - name: login dockerhub
              uses: docker/login-action@v3
              with:
                username: ${{ env.USERNAME }}
                password: ${{ env.MY_SECRET_TOKEN_DOKERHUB }}
            - name: checkout code
              uses: actions/checkout@v4
            - name: build docker image
              run: docker build -t $USERNAME/toon .
            - name: push dockerhub
              run: docker push $USERNAME/toon